### ISSUE TITLE
PollUpdate error in the absence of bot token

### ISSUE THREAD

**Issue by OceaneCsn** [AdrienJarretier/visualisation-cas-covid-19#26]
PollUpdate shouldn't start without bot

**Comment by hugodecasta** [comment]
Can you be more precise

**Comment by OceaneCsn** [comment]
When starting the app without the telegram bot, got the following error : 

```
(node:12208) UnhandledPromiseRejectionWarning: TypeError: results is not iterable
    at pollUpdates (D:\visualisation-cas-covid-19\telegram-notifications-bot-controler\control.js:110:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

The error doesn't appear when the following lines in control.js are commented : 

```
pollUpdates(function (result) {

  if (result.message.entities) {

    let containsStart = false;

    for (let entity of result.message.entities) {

      if (entity.type == 'bot_command') {

        if (result.message.text.startsWith('/start')) {

          containsStart = true;
        }

      }

    }

    if (containsStart) {

      commandHandlers.start(result.message);

    }
  }
});
```

**Comment by hugodecasta** [comment]
Fixed by adding an ```analbed``` prop to the telegram bot config 4a1da43d7959e4d296985b61622be9c15ae60c2f
